development:
  adapter: mysql2
  encoding: utf8
  database: mydb
  username: www
  password: www
  host: 192.168.0.103
  port: 3306
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  encoding: utf8
  database: mydb
  username: www
  password: www
  host: 192.168.0.103
  port: 3306
  socket: /tmp/mysql.sock
  pool: 5
  timeout: 5000
production:
   adapter: mysql2
   encoding: utf8
   database: mydb
   username: www
   password: www
   host: 192.168.0.103
   port: 3306
   socket: /tmp/mysql.sock
   pool: 5
   timeout: 5000